### ISSUE TITLE
Speed information lost

### ISSUE THREAD

**Issue by ebartik** [drakhart/ha-super-soco-custom#12]
Hello,

I would like to ask for help with speed values. I use the lastest version for several weeks with no issue but from last week, I recognize no speed info received via Vmoto Soco login. Used version is [1.0.0-beta.11]. Below, you can find an error related to this app:
-----------------------------------------------------------------------------------------------------------------------
Logger: custom_components.super_soco_custom
Source: custom_components/super_soco_custom/vmoto_soco_api.py:121
Integration: Super Soco Custom ([documentation](https://github.com/drakhart/ha-super-soco-custom), [issues](https://github.com/drakhart/ha-super-soco-custom/issues))
First occurred: 14. června 2023 v 07:15:50 (3000 occurrences)
Last logged: 12:57:20

999, message='', url=URL('https://app.vmotosoco-service.com/app/v1/deviceWarn/findDeviceWarnPageByUserId')
Traceback (most recent call last):
  File "/config/custom_components/super_soco_custom/coordinator.py", line 542, in _get_last_warning_data
    res = await self._client.get_warning_list(self._user_id, 1, 1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/super_soco_custom/vmoto_soco_api.py", line 75, in get_warning_list
    return await self._api_wrapper(url, headers, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/super_soco_custom/vmoto_soco_api.py", line 121, in _api_wrapper
    res.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 999, message='', url=URL('https://app.vmotosoco-service.com/app/v1/deviceWarn/findDeviceWarnPageByUserId')
-----------------------------------------------------------------------------------------------------------------------

The login is validated, other data are coming, namely CPX Last GPS Time is changing, therefore I expect the authentication is valid and working properly.

Is there anything I can check?

Thank you

Michal

**Comment by drakhart** [comment]
Hi, @ebartik. I experienced the same issue at about the same time as you. I still don't know what happened, but reloading the integration worked fine for me. Can you please try that and report if that worked for you too?

Thanks in advance.

**Comment by ebartik** [comment]
Hi @drakhart, I really reloaded but didn't help in terms of speed info. I also tried to re-register but no success.

Thanks a have a nice day :)

**Comment by drakhart** [comment]
Hi @ebartik. Ok, I'll try to investigate a bit and see if this is another error coming from Super Soco or something that I can fix on the integration. Lately I don't have much time though, so please bear with me.

Thanks.

**Comment by ebartik** [comment]
Hi @drakhart, it would be great if you have a look, I like the integration very much. No matter if it takes some time :).

Thanks a lot

**Comment by ebartik** [comment]
Hi @drakhart. I just found out that the speed information is back. This week, the app asked for new SMS validation and since then, it came back. Since the speed info issue (in June), I did the validation few times but didn't help. Besides that, no modification was done by me.

**Comment by drakhart** [comment]
Thanks for the update, @ebartik. I'll take that into account and try to come up with a fix asap.

**Comment by ebartik** [comment]
Hi @drakhart, I can really confirm that, the speed info is working properly since then. Thanks!

**Comment by drakhart** [comment]
Thanks! I'm closing the issue as resolved.
