### ISSUE TITLE
Need to reload integration all the time

### ISSUE THREAD

**Issue by apbarratt** [drakhart/ha-super-soco-custom#13]
## Version of the custom_component

Latest and kept up to date as updates appear :)
I use the newer vmoto app with the battery-powered ECU on a TC-Max.

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
This whole integration was working very well for me, but recently I find it constantly requires a reload to get certain parts to work.  It does seem that most data is still coming through, but the most notable issue is when I go to turn on the bike's power and the power toggles (along with the other toggles for notifications etc) are all greyed out.  This is fairly quickly repaired by just going to the integration page and choosing "Reload".  After about 20 seconds of waiting, the toggle comes back, I can turn on my bike, move it out of the way of my bins to bring them out for the bin lorry and I'm sorted.  But if I check even minutes later I can see the toggles have greyed out again.

I almost wonder if Vmoto have updated the app to only provide certain settings if the logged-in session checks in somehow.  Frequent polling would undoubtedly be a bad idea, but perhaps if we could stick some kind of retain time to keep the switch status up to date and check once an hour or so and have the command to send include whatever the check-in requirement is... I'm absolutely guessing here 😅

## Debug log

```text

Please advice what sort of logs I can provide and how :)
If there's also some way to volunteer live data logs to you to check in on, I'd be happy to provide that if having access to another device would assist in your efforts, though obviously it'd need to be done in some way that is not public :) 

```

**Comment by apbarratt** [comment]
Hi @drakhart, is there anything I can do to assist with investigating this one? :)

**Comment by drakhart** [comment]
Hi @apbarratt. I think this issue is related to #10: the response doesn't return a last warning time, then the integration sets that state as unknown and the new HA versions don't like that, so it starts failing.

I think I have found a fix, but I need to try it a bit more just to make sure. Will let you know the outcome asap.

**Comment by apbarratt** [comment]
Fair enough, I've disabled the last warning entity, will see how things go after another reload :)

**Comment by drakhart** [comment]
This should have been fixed in [beta 12](https://github.com/drakhart/ha-super-soco-custom/releases/tag/1.0.0-beta.12). Please let me know if that worked for you.

**Comment by drakhart** [comment]
There hasn't been any response for a long time, and I assume this has been already fixed as mentioned in my previous comment.
