### ISSUE TITLE
Workflows targeting `main` but primary branch called `master`

### ISSUE THREAD

**Issue by apbarratt** [drakhart/ha-super-soco-custom#21]
The GitHub workflows are currently targeting `main` but the primary branch on the repo is still called `master`.

One of the two needs to change.  I like the idea of using `main` more and with there only being three forks right now and mine the only one active in the last two years, it really shouldn't be too much trouble to update my fork as appropriate after the change is made :)

**Comment by drakhart** [comment]
Fixed renaming `master` branch to `main`.
