### ISSUE TITLE
Stuck in the Reconfiguration V1.0.0 Beta

### ISSUE THREAD

**Issue by Xnygra** [drakhart/ha-super-soco-custom#7]
Thank you for the much anticipated update, 

Unfortunately i cannot get it to work. I have updated through HACS and get to the Reconfiguration menu, but get this error message
"Invalid authentication or too many verification codes requested", even though I have not yet submitted my phone number, the same if a do a restart of HA (as I cant restart the integration, as below) or if I wait a solid 24h before try to Reconfigure again.

on the menu when clicking the three dots, I only get a Documentation chose, I would like to have a Reload and a Delete option, to have a clean restart. 

Thank you for the effort you have put into this.

**Comment by drakhart** [comment]
Hi @Xnygra. I'm sorry for the inconvenience, but as I mentioned this release has many changes that can be problematic for an update even if I tried to add a version migration step. My recommendation is that you try to remove the integration and configure it from scratch, and see if that helps.

If it doesn't please let me know.

**Comment by drakhart** [comment]
This should be fixed in [release 1.0.0-beta.9](https://github.com/drakhart/ha-super-soco-custom/releases/tag/1.0.0-beta.9), but as I mention in the changelog only "for new updates (unfortunately I don't think this fix will work if you already tried to update, sorry)".

**Comment by drakhart** [comment]
Update: I've pinpointed the issue to a temporal token that the app sends along with the phone number. I thought it was a static code and copied it into the integration, but turns out that it's a unique code for each phone number.

I'll need to decompile the application, see how it generates these codes and copy that functionality into this integration. It will take some time, so please bear with me and I'll update you as soon as I have a fix in place.

**Comment by drakhart** [comment]
Ok, this was faster than what I expected: it should be fixed in [release 1.0.0-beta.10](https://github.com/drakhart/ha-super-soco-custom/releases/tag/1.0.0-beta.10). Please let me know if it works for you. Thanks.

**Comment by Xnygra** [comment]
Sweet, thank you. It works now. 

Got stuck in another error, but this ticket can be closed and I open up a new. 

Thank you for the time and effort you put into this.
